version: "3.7"

services:
  wol-server:
    image: amrap030/wol-wake-on-lan:latest
    container_name: wol-server
    ports:
      - "3000:3000"
    restart: "unless-stopped"
    environment:
      - LOG_DIR=${LOG_DIR:-/var/log/wol}
      - LOG_FORMAT=${LOG_FORMAT:-combined}
      - MAC_ADDRESS=${MAC_ADDRESS}
      - ORIGIN=${ORIGIN}
      - PASSWORD=${PASSWORD}
      - PORT=${PORT:-3000}
      - SERVER=${SERVER}
    network_mode: "host"
